cursor #eedfe3
cursor_text_color #d4c2c8

foreground            #eedfe3
background            #181115
selection_foreground  #402a35
selection_background  #e0bdcc
url_color             #fcb0d5

color0   #181115
color1   #ff727a
color2   #9ffc7e
color3   #ffe172
color4   #ef98c2
color5   #743453
color6   #fcb0d5
color7   #ffeff7
color8   #a3979d
color9   #ff9fa4
color10  #bdffa5
color11  #ffeba5
color12  #ffbddd
color13  #ffc9e3
color14  #ffdced
color15  #fff8fb
