[colors]
background = '#151218'
foreground = '#e7e0e8'

cursor_bg = '#d7bafb'
cursor_fg = '#151218'
cursor_border = '#d7bafb'

selection_bg = '#533b72'
selection_fg = '#e7e0e8'

ansi = ['#151218', '#ff728c', '#7dfb99', '#ffdb72', '#c5a4ee', '#553d74', '#d7bafb', '#f6efff']
brights = ['#9c96a3', '#ff9fb1', '#a5ffb9', '#ffe8a5', '#dfc6ff', '#e5d0ff', '#eee1ff', '#fbf8ff']
