[colors]
background = '#0e1415'
foreground = '#dee4e4'

cursor_bg = '#81d4dd'
cursor_fg = '#0e1415'
cursor_border = '#81d4dd'

selection_bg = '#004f55'
selection_fg = '#dee4e4'

ansi = ['#0e1415', '#fe72a3', '#6edd78', '#fff572', '#69c7d1', '#185e66', '#81d4dd', '#dae6e8']
brights = ['#848e8f', '#ff9fc0', '#a5ffad', '#fff8a5', '#9deaf3', '#b4f7ff', '#cffaff', '#f8feff']
