[colors]
background = '#181115'
foreground = '#eedfe3'

cursor_bg = '#fcb0d5'
cursor_fg = '#181115'
cursor_border = '#fcb0d5'

selection_bg = '#6c3353'
selection_fg = '#eedfe3'

ansi = ['#181115', '#ff727a', '#9ffc7e', '#ffe172', '#ef98c2', '#743453', '#fcb0d5', '#ffeff7']
brights = ['#a3979d', '#ff9fa4', '#bdffa5', '#ffeba5', '#ffbddd', '#ffc9e3', '#ffdced', '#fff8fb']
